spring:
  application:
    name: 11-Swagger-External-API
  datasource:
    url: jdbc:h2:mem:movies
    username: sa
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    web: debug
omdb:
  api-key: APIKEY